apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-ns
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "8080"
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        env:
        - name: JAVA_OPTS
          value: "-Djenkins.install.runSetupWizard=false"
        - name: JENKINS_OPTS
          value: "--httpPort=8080"
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins-ns
spec:
  selector:
    app: jenkins
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: agent
    port: 50000
    targetPort: 50000
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-config
  namespace: jenkins-ns
data:
  plugins.txt: |
    kubernetes:1.30.0
    workflow-aggregator:2.6
    git:4.8.2
    credentials-binding:1.27
    timestamper:1.13
    pipeline-stage-view:2.19
    blueocean:1.25.3
    job-dsl:1.77
    configuration-as-code:1.55
    prometheus:2.0.11
  casc.yaml: |
    jenkins:
      systemMessage: "Jenkins configured automatically by JCasC"

    unclassified:
      prometheusConfiguration:
        collectDiskUsage: true
        collectNodeStatus: true
        collectQueueMetrics: true
        collectJobMetrics: true
        path: /prometheus
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secrets
  namespace: jenkins-ns
type: Opaque
data:
  admin-password: YWRtaW4=   # base64(admin)
---
apiVersion: batch/v1
kind: Job
metadata:
  name: jenkins-init
  namespace: jenkins-ns
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: init
        image: jenkins/jenkins:lts
        command: ["/bin/sh", "-c"]
        args:
        - |
          cp /usr/share/jenkins/ref/plugins.txt /var/jenkins_home/plugins.txt && \
          /usr/local/bin/install-plugins.sh < /var/jenkins_home/plugins.txt && \
          cp /usr/share/jenkins/ref/casc.yaml /var/jenkins_home/casc.yaml
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        - name: config
          mountPath: /usr/share/jenkins/ref
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pvc
      - name: config
        configMap:
          name: jenkins-config
      restartPolicy: Never